language: python
python:
# geenote uses features of python not present in 2.6
#  - "2.6"
  - "2.7"
# The official Evernote SDK doesn't support Python 3 yet
# Keep an eye on https://github.com/evernote/evernote-sdk-python3
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

os:
  - linux
  - osx

install:
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install --bash-completion-dir=/tmp --zsh-completion-dir=/tmp

# there's no interactive editor here, so use cat
env:
- EDITOR=/bin/cat

# command to run tests
script: py.test
